services:
  # 1. TU BACKEND (Spring Boot)
  backend-canchapp:
    build: ./CanchAPP_Back
    restart: unless-stopped
    container_name: backend_canchapp
    ports:
      - "3601:8080" # Exponemos el 8080 por si necesitas pegarle a la API directo desde Postman
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    networks:
      - internal-canchapp

  # 2. TU FRONTEND (React)
  frontend-canchapp:
    build: ./canchapp-frontend
    restart: unless-stopped
    container_name: frontend_canchapp
    ports:
      - "3101:80" #
    depends_on:
      - backend-canchapp
    networks:
      - internal-canchapp

networks:
  internal-canchapp:
    driver: bridge
